apiVersion: webconsole.config.openshift.io/v1
clusterInfo:
  consolePublicURL: https://babak-master.cloud.lab.eng.bos.redhat.com:8443/console/
  loggingPublicURL: https://kibana.babak.ocp.cloud.lab.eng.bos.redhat.com
  logoutPublicURL: ''
  masterPublicURL: https://babak-master.cloud.lab.eng.bos.redhat.com:8443
  metricsPublicURL: ''
extensions:
  properties: {}
  scriptURLs: []
  stylesheetURLs: []
features:
  clusterResourceOverridesEnabled: false
  inactivityTimeoutMinutes: 0
kind: WebConsoleConfiguration
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: /var/serving-cert/tls.crt
  clientCA: ''
  keyFile: /var/serving-cert/tls.key
  maxRequestsInFlight: 0
  namedCertificates: null
  requestTimeoutSeconds: 0